helptime/events/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path

from . import views

app_name = "events"
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("eventupdate/<int:pk>", views.eventupdate, name="eventupdate"),  
    path("taskupdate/<int:pk>", views.taskupdate, name="taskupdate"),  
    path("tasklist/<int:pk>", views.tasklist, name="tasklist"),  
    path("eventdelete/<int:pk>", views.eventdelete, name="eventdelete"),
    path("volunteer/<int:pk>", views.volunteer, name="volunteer")
]

helptime/helptime/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .import views

from .import views

urlpatterns = [ 
    path('', views.index),
    path('events/', include("events.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helptime/events/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime




class Event(models.Model):
    reminder_days_choice = models.TextChoices('days', '1 2 3 4 5 6 7')
    
    name = models.CharField(max_length=200, verbose_name='Event Name' )
    description = models.TextField(max_length=200, verbose_name='Event Description', blank=True)
    organization = models.CharField(max_length=100, verbose_name='Organization Name', blank=True )
    primery_contact = models.CharField(max_length=100, verbose_name='Primary Contact', blank=True)
    alternate_contact = models.CharField(max_length=100, verbose_name='Alt Contact', blank=True)
    hide_names = models.BooleanField(default=False, verbose_name='Hide Volunteer Names', blank=True)
    reminder_days = models.CharField(max_length=5, choices=reminder_days_choice, verbose_name='Days to remind in advance', default=7)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name

class Task(models.Model):

    task = models.CharField(max_length=200, verbose_name='Task Name' )
    description = models.CharField(max_length=200, verbose_name='Event Description', blank=True)
    task_date = models.DateField(verbose_name='Task Date', null=True, blank=True)
    start_time = models.TimeField(verbose_name='Start Time',null=True ,blank=True)
    end_time = models.TimeField(verbose_name='End Time ', null=True,blank=True )
    volunteer =models.CharField(max_length=100, verbose_name='Volunteer',  null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.SET_NULL,  null=True, blank=True, related_name='tasks')

    def __str__(self):
        return self.task
    

helptime/events/forms.py
from django import forms
from django.forms import DateInput, ModelForm
from django.contrib.admin import widgets     

from .models import Event, Task

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields= '__all__'
        widgets = {
            'hide_names' :  forms.CheckboxInput(
                attrs={'class' : 'form-check_input'})
        }



class EventCreateForm(forms.ModelForm):
    class Meta:
        model = Event
        fields= ['name']
        widgets = {
            'name' :  forms.TextInput(
                attrs={'placeholder': 'New Event Name'}),
        }

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields= '__all__'
        widgets = {
            'task' :  forms.TextInput(
                attrs={'placeholder': 'New Task Name'}),
            'task_date' : DateInput(),
            'start_time' : TimeInput(),
            'end_time' : TimeInput(),
        }

class EventSearchForm(forms.Form):
    filter = forms.CharField(required=False, 
                             label="",
                             widget=forms.TextInput(attrs={'placeholder':'Search',
                                                           'class':'form-control'}))

helptime/events/views.py
from django.http import HttpResponse, HttpResponseRedirect  # noqa: 401
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Event, Task
from .forms import EventForm, EventCreateForm, TaskForm, EventSearchForm
from django.db.models import Q, Min, Max, Count


def index(request):
    form = EventSearchForm(request.GET or None)
    
    events = Event.objects.annotate(
        start_task_date=Min('tasks__task_date'),
        end_task_date=Max('tasks__task_date')
    )

    if form.is_valid():
        filter = form.cleaned_data.get('filter')
        events = events.filter(Q(name__icontains=filter) | Q(organization__icontains=filter))
    
    context = {
        'form' : form,
        'events' : events,
    }

    return render(request, 'events/index.html', context) 


@login_required  #forces a login
def dashboard(request):
    # Authenticated user listing
    events = Event.objects.filter(Q(created_by=request.user)).annotate(
        start_task_date=Min('tasks__task_date'),
        end_task_date=Max('tasks__task_date'),
        count_task=Count('tasks'))
    
    form = EventCreateForm()
    if request.method == 'POST':
        form = EventCreateForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            #new_item.created_by = request.user
            new_item = form.save()
            return redirect ('events:eventupdate', new_item.pk)
    return render(request, 'events/dashboard.html', {'events' : events, 'form':form}) #to a template empty {} if no context 
  

#@login_required  #forces a login
def eventupdate(request, pk): 
    # Access to events that user has created or has no creator
    if request.user.is_authenticated:
        event = Event.objects.get(Q(id=pk), (Q(created_by=request.user) | Q(created_by=None)) )
    else:
        event = Event.objects.get(Q(id=pk), (Q(created_by=None)) )
    form = EventForm(instance=event)
   
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)

        if form.is_valid():
            if event.created_by is None: # Set the created by field if null
                #if the user authenticated then ..
                if request.user.is_authenticated:
                    event.created_by = request.user
            form.save()
            if 'ToTasks' in request.POST:
                return redirect('events:tasklist', pk=event.id)
    return render(request, 'events/eventupdate.html', {'form':form, 'event':event})

@login_required  #forces a login
def eventdelete(request,pk):
    event = Event.objects.get(id=pk)

    if request.method == 'POST':
        event.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return render (request, 'events/eventdelete.html', {'event': event})


@login_required  #forces a login
def tasklist(request, pk):
    tasks = Task.objects.filter(event_id=pk)
    events = Event.objects.filter(id=pk)
    event_id = pk

    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.event_id = event_id
            new_item = form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            #return redirect ('events:tasklist', event_id)
        
    return render(request, 'events/tasklist.html', { 'tasks': tasks , 'events' : events, 'form':form})
    
@login_required  #forces a login
def taskupdate(request, pk): 
    tasks = Task.objects.get(id=pk)
    form = TaskForm(instance=tasks)
    event_id = tasks.event_id

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=tasks)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.event_id = event_id
            new_item = form.save()
            return redirect ('events:tasklist', event_id)
    return render(request, 'events/taskupdate.html', {'form': form, 'tasks':tasks})

def volunteer(request,pk):
    tasks = Task.objects.filter(event_id=pk)
    events = Event.objects.filter(id=pk)
    event_id = pk

    form = TaskForm()
    form.volunteer = "tru"
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.event_id = event_id
            new_item.volunteer = "try"
            new_item = form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            #return redirect ('events:tasklist', event_id)
        
    return render(request, 'events/volunteer.html', { 'tasks': tasks , 'events' : events, 'form':form})

helptime/events/templates/events/dashboard.html
{% extends 'master.html' %}

{% block content %}
<h1> My Dashboard</h1>
<div class="float-end">
    <form action="" method="post">
        {% csrf_token %}
        {{form.name}}
        <input type="submit" value="Save and Continue" class="btn-success" />
    </form>
</div>


{% if events %}
    <p>These are events your created</p>
{% else %}
    <p>No events are available.</p>
{% endif %}


<table class="table">
    <tr>
        <th>Event Name</th>
        <th># Tasks</th>
        <th>Start Date</th>
        <th>End Date</th>
    </tr>
    {% for event in events %}
    <tr>
        <td>{{ event.name }}
            <a href="{% url 'events:eventupdate' event.id %}" class="text-success"><i class="bi bi-pencil"></i></a>
            <a href="{% url 'events:eventdelete' event.id %}" class="text-danger"><i class="bi bi-trash "></i></a>
            <a href="{% url 'events:volunteer' event.id %}" class="text-success"><i class="bi bi-person-raised-hand h4 text-success"></i>

            

        </td>
        <td><a href="{% url 'events:tasklist' event.id %}" class="text-primary">{{ event.count_task }}</a></td>
        <td>{{ event.start_task_date | date:"m/d/Y" }} </td>
        <td>{{ event.end_task_date | date:"m/d/Y"}} </td>
        

    </tr>


    {% endfor %}
</table>



{% endblock %}

helptime/events/templates/events/delete.html
{% extends 'master.html' %}

{% block content %}

<h1>Delete</h1>

<h4>Do you really want to delete?
    <strong>"{{ todo }}"</strong>
</h4>


<a href="{% url 'events:index' %}">Cancel - do NOT delete</a></div>

<form method="POST" class="form container">
    {% csrf_token %}
    <input type ='submit' value="Confirm Delete" class="btn-primary">
</form>

{% endblock %}

helptime/events/templates/events/detail.html
{% extends 'master.html' %}

{% block content %}

<h1>Welcome to Event Detail page</h1>

<h2>Event: {{ event.name }}</h2>
<p> Description: {{ event.description }} p </p>

<table class="table"> {{ event }}   table </table>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{{ task }}

{% endblock %} 

helptime/events/templates/events/eventdelete.html
{% extends 'master.html' %}

{% block content %}

<h1>Delete</h1>

<h4>Do you really want to delete the event called > 
    <strong>"{{ event.name }}"</strong>
</h4>


<a href="{{request.META.HTTP_REFERER}}">Cancel - do NOT delete</a></div>

<form method="POST" class="form container">
    {% csrf_token %}
    <input type ='submit' value="Confirm Delete" class="btn-primary">
</form>

{% endblock %}

helptime/events/templates/events/eventupdate.html
{% extends 'master.html' %}

{% block content %}

<h1> Maintain Event Information </h1>
<form method="POST" class="container-float">
    <fieldset>
        {% csrf_token %}
        <div class="row">
            <strong>{{form.name.label}}</strong>
            {{ form.name}}
        </div>
        <div class="row mt-3">
            <strong>{{form.description.label}}</strong>
            {{ form.description}}
        </div>
        <div class="row mt-3">
            <strong>{{form.organization.label}}</strong>
            {{ form.organization}}
        </div>
        <div class="row mt-1">
            <strong>{{form.primery_contact.label}}</strong>
            {{ form.primery_contact}}
        </div>
        <div class="row mt-1">
            <strong>{{form.alternate_contact.label}}</strong>
            {{ form.alternate_contact}}
        </div>
        <div class="row mt-3">
            <div class="col-md-6 form-switch-input">
                <strong>{{form.hide_names.label}}</strong>
                {{ form.hide_names }}
            </div>
            <div class="col-md-6">
                <strong>{{form.reminder_days.label}}</strong>
                {{ form.reminder_days}}
            </div>
        </div>

    </fieldset>
    <div class="mt-3">
        {% if user.is_authenticated %}
            <a href="{% url 'events:dashboard' %}" class='float-right btn btn-warning pull-right'>Back</a>
        {% else %}
            <a href="{% url 'events:index' %}" class='float-right btn btn-warning pull-right'>Back</a>
        {% endif %}
        
        <input type="submit" value="Save" class='float-right btn btn-success pull-right'>
        <a href="{% url 'events:eventdelete' event.id %}" class="text-danger"><span class="float-right btn btn-danger pull-right">Delete</span></a>
        <input type="submit" name="ToTasks" value="Maintain Tasks" class='float-right btn btn-primary pull-right'>
    </div>
</form>

{% endblock %}

helptime/events/templates/events/index.html
{% extends 'master.html' %}

{% block content %}

    <div class="row">
        <div class="col-sm-6">
            <h1> Event Listing</h1>
        </div>
        <div class="col-sm-6">
            <div class="float-end">
                <form method="get">
                    <div class="input-group mb-2">
                        {{form}}
                        <button type="submit"> <i class="bi bi-search text-success"></i> </button>
                    </div>
                </form>
            </div>
        </div>
    </div>










<table class="table">
    <tr>
        <th>Event Name</th>
        <th>Start Date</th>
        <th>End Date</th>
    </tr>
    {% for event in events %}
    <tr>
        <td><a href="{% url 'events:volunteer' event.id %}" class="text-success"><span class="text-primary-emphasis">{{ event.name  }} </span><i class="bi bi-person-raised-hand text-success"></i>
            {% if event.created_by is None %}
              {% if user.is_authenticated %}
                <a href="{% url 'events:eventupdate' event.id %}" class="text-success"><i class="bi bi-pencil"></i></a>
                <a href="{% url 'events:eventdelete' event.id %}" class="text-danger"><i class="bi bi-trash "></i></a>
              {% else %}
                <a class="text-warning small" href="{% url 'login' %}?next={{ request.path }}">Login to claim this event</a>
            
              {% endif %}
            {% endif %}
        </td>
            
        <td>{{ event.start_task_date | date:"m/d/Y" }} </td>
        <td>{{ event.end_task_date | date:"m/d/Y"}} </td>

    </tr>


    {% endfor %}
</table>



{% endblock %}

helptime/events/templates/events/tasklist.html
{% extends 'master.html' %}

{% block content %}
<div class="row">
    <div class="col-md-10">
        <h1> Task List :{% with event=events|first %}
            <strong>{{ event.name}}</strong>
        </h1>
    </div>
    <div class="col-md-2">
        <a href="{{request.META.HTTP_REFERER}}" class='btn btn-warning float-end'>Go Back</a>
    </div>
</div>

 {% endwith %}

 <form method="POST" class="">
    {% csrf_token %}

    <div class="table-responsive">
        <table class="table">
            <tr class="bg-info">
                <th>Task Name</th>
                <th>Description</th>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Volunteer</th>
            </tr>
            {% for task in tasks %}
            <tr>
                <td>{{ task.task }}
                    <a href="{% url 'events:taskupdate' task.id %}" class="text-success"><i class="bi bi-pencil"></i></a>
                </td>
                <td>{{ task.description }} </td>
                <td>{{ task.task_date | date:"m/d/Y"}} </td>
                <td>{{ task.start_time }} </td>
                <td>{{ task.end_time }}</td>
                <td>{{ task.volunteer }}</td>
            </tr>

            {% endfor %} <div class="mt-3 float-end">
        </table>
    </div>

</form>
<hr>
<h2>Add a New Task</h2>
<div class="row">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% csrf_token %}
            <div class="row">
                <strong>{{form.task.label}}</strong>
                {{ form.task }}
            </div>
            <div class="row mt-3">
                <strong>{{form.description.label}}</strong>
                {{ form.description }}
            </div>
            <div class="row mt-3">
                <div class="col-md-4">
                    <strong>{{form.task_date.label}}</strong>
                    {{ form.task_date}}
                </div>
                <div class="col-md-4">
                    <strong>{{form.start_time.label}}</strong>
                    {{ form.start_time}}
                </div>
                <div class="col-md-4">
                    <strong>{{form.end_time.label}}</strong>
                    {{ form.end_time}}
                </div>
            </div>
            <div class="row mt-3">
                <strong>{{form.volunteer.label}}</strong>
                {{ form.volunteer }}
            </div>

        </fieldset>
        <div class="float-end">
            <input type="submit" value="Add task" class="btn-success" />
        </div>
    </form>
</div>



<pre>


</pre>

{% endblock %}

helptime/events/templates/events/taskupdate.html
{% extends 'master.html' %}

{% block content %}

<h1> Maintain Task Information </h1>
<h2>Event: {{ task.event.name }}</h2>
<form method="POST" class="container-float">
    {% csrf_token %}
    <fieldset>
        {% csrf_token %}
        <div class="row">
            <strong>{{form.task.label}}</strong>
            {{ form.task }}
        </div>
        <div class="row mt-3">
            <strong>{{form.description.label}}</strong>
            {{ form.description }}
        </div>
        <div class="row mt-3">
            <div class="col-md-4">
                <strong>{{form.task_date.label}}</strong>
                {{ form.task_date | date:"m/d/Y" }}
            </div>
            <div class="col-md-4">
                <strong>{{form.start_time.label}}</strong>
                {{ form.start_time}}
            </div>
            <div class="col-md-4">
                <strong>{{form.end_time.label}}</strong>
                {{ form.end_time}}
            </div>
        </div>
        <div class="row mt-3">
            <strong>{{form.volunteer.label}}</strong>
            {{ form.volunteer }}
        </div>

    </fieldset>

    <div class="mt-3">
        <a href="{% url 'events:index' %}" class='float-right btn btn-warning'>Cancel</a>
        <input type="submit" value="Save Updates" class='float-right btn btn-success'>
    </div>
    
</form>

{% endblock %}

helptime/events/templates/events/update.html
{% extends 'master.html' %}

{% block content %}

<h1> Maintain Event Information </h1>
<form method="POST" class="container-float">
    <fieldset>
        {% csrf_token %}
        <div class="row">
            <strong>{{form.name.label}}</strong>
            {{ form.name}}
        </div>
        <div class="row mt-3">
            <strong>{{form.description.label}}</strong>
            {{ form.description}}
        </div>
        <div class="row mt-3">
            <strong>{{form.organization.label}}</strong>
            {{ form.organization}}
        </div>
        <div class="row mt-1">
            <strong>{{form.primery_contact.label}}</strong>
            {{ form.primery_contact}}
        </div>
        <div class="row mt-1">
            <strong>{{form.alternate_contact.label}}</strong>
            {{ form.alternate_contact}}
        </div>
        <div class="row mt-3">
            <div class="col-md-6 form-switch-input">
                <strong>{{form.hide_names.label}}</strong>
                {{ form.hide_names }}
            </div>
            <div class="col-md-6">
                <strong>{{form.reminder_days.label}}</strong>
                {{ form.reminder_days}}
            </div>
        </div>

    </fieldset>
    <div class="mt-3">
        <a href="{% url 'events:index' %}" class='float-right btn btn-warning pull-right'>Cancel</a>
        <input type="submit" value="Save Updates" class='float-right btn btn-success pull-right'>
    </div>
</form>
<pre>


</pre>

{% endblock %}

helptime/events/templates/events/volunteer.html
{% extends 'master.html' %}

{% block content %}

<h1>Signup and Volunteer</h1>

{% with event=events|first %}
    <h2>Event: {{ event.name }}</h2>
    <p> Description: {{ event.description }} </p>
{% endwith %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
 

<form method="POST" class="">
    {% csrf_token %}
    <div class="table-responsive">
        <table class="table">
            <tr class="bg-info">
                <th>Task Name</th>
                <th>Description</th>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Volunteer</th>
            </tr>
            {% for task in tasks %}
            <tr>
                <td>{{ task.task }}</td>
                <td>{{ task.description }} </td>
                <td>{{ task.task_date | date:"m/d/Y"}} </td>
                <td>{{ task.start_time }} </td>
                <td>{{ task.end_time }}</td>
                <td>{{ form.volunteer }}</td>
            </tr>

            {% endfor %} <div class="mt-3 float-end">
        </table>
    </div>
    <input type="submit" value="Save" class="btn-success" />
</form>



{% endblock %} 